import { test, expect } from '@playwright/test';
import { openFixture, collectErrors, scrollToY, read, call, sweep, table } from './helpers';

/**
 * `scrollVideo` in real browsers.
 *
 * jsdom has no media pipeline: `duration` is NaN, `currentTime` is a plain
 * property nothing enforces, `readyState` never advances past 0 and
 * `loadedmetadata` never fires. So the unit tests can only check that the engine
 * assigns a number to a property on a fake object — every interesting question
 * (does the frame change, what happens before metadata arrives, does seeking a
 * real decoder keep up) needed a real browser and a real file.
 *
 * The clip is generated by `scripts/make-fixture-video.mjs`: 4s, 10fps, every
 * frame a solid unique grey and its own keyframe.
 *
 * Fixture geometry (viewport 900x800): #clip at document top 1200, 400 tall.
 * Default window `top top` → `bottom top` gives tStart=1200, tEnd=1600.
 */

type Row = {
  scrollY: number;
  currentTime: number;
  duration: number | null;
  paused: boolean;
  readyState: number;
  seeking: boolean;
  readyCalls: number;
  progressCount: number;
  brokenTime: number;
  brokenReadyState: number;
  brokenReadyCalls: number;
};

const T_START = 1200;
const T_END = 1600;
const DURATION = 4;
const FPS = 10;

const alphaAt = (y: number) => Math.min(1, Math.max(0, (y - T_START) / (T_END - T_START)));
/** The fixture generator's frame colour, so the spec can invert a pixel to a frame. */
const greyForTime = (t: number) => (Math.min(Math.floor(t * FPS), FPS * DURATION - 1) * 6) % 256;

async function requireDecoder(page: import('@playwright/test').Page) {
  const canDecode = await call<boolean>(page, 'canDecode');
  // A skip, never a silent pass: if a browser cannot decode the fixture at all
  // there is nothing to measure, and reporting "passed" would be exactly the
  // "unmeasured rendered as passed" failure Phase 1 was burned by.
  test.skip(!canDecode, 'browser cannot decode VP8/WebM, so the clip cannot be scrubbed');
}

test.describe('scrollVideo', () => {
  test('loads the clip and reports real metadata', async ({ page }) => {
    const errors = collectErrors(page);
    await openFixture(page, 'video.html');
    expect(errors).toEqual([]);

    expect(
      await call<{ clipTop: number; clipHeight: number; viewport: number }>(page, 'geometry'),
    ).toEqual({ clipTop: 1200, clipHeight: 400, viewport: 800 });

    await requireDecoder(page);
    await expect.poll(async () => (await read<Row>(page)).readyState, { timeout: 5000 }).toBeGreaterThanOrEqual(1);

    const row = await read<Row>(page);
    expect(row.duration).toBeCloseTo(DURATION, 1);
    expect(row.readyCalls, 'onReady should fire exactly once').toBe(1);
    // A scrubbed video must never be playing — the scroll position is the clock.
    expect(row.paused, 'video should stay paused').toBe(true);
  });

  test('currentTime tracks the scroll position', async ({ page }) => {
    await openFixture(page, 'video.html');
    await requireDecoder(page);
    await expect.poll(async () => (await read<Row>(page)).duration, { timeout: 5000 }).not.toBeNull();

    const offsets = [T_START, 1300, 1400, 1500, T_END];
    const rows = await sweep<Row>(page, offsets);
    const shown = table(
      rows.map((r) => ({
        y: r.scrollY,
        currentTime: r.currentTime,
        want: DURATION * alphaAt(r.scrollY),
      })),
    );

    for (const r of rows) {
      // Default easing is linear, so this is an exact mapping, not a trend.
      expect(r.currentTime, `currentTime wrong at y=${r.scrollY}\n${shown}`).toBeCloseTo(
        DURATION * alphaAt(r.scrollY),
        1,
      );
    }
    expect(rows[0].currentTime, shown).toBeCloseTo(0, 1);
    expect(rows[rows.length - 1].currentTime, shown).toBeCloseTo(DURATION, 1);
  });

  test('the browser actually paints the frame for the scrubbed time', async ({ page }) => {
    await openFixture(page, 'video.html');
    await requireDecoder(page);
    await expect.poll(async () => (await read<Row>(page)).duration, { timeout: 5000 }).not.toBeNull();

    const samples: { y: number; time: number; grey: number; want: number }[] = [];

    for (const y of [T_START, 1300, 1400, 1500]) {
      await scrollToY(page, y);
      // Wait for the decoder to finish the seek before reading pixels, otherwise
      // the canvas holds the previous frame and the test measures latency.
      await expect.poll(async () => (await call<{ seeking: boolean }>(page, 'paint')).seeking, {
        timeout: 5000,
      }).toBe(false);

      const p = await call<{ grey: number; currentTime: number }>(page, 'paint');
      samples.push({ y, time: p.currentTime, grey: p.grey, want: greyForTime(p.currentTime) });
    }

    const shown = table(samples);
    for (const s of samples) {
      // ±12 grey levels is ±2 frames of the generator's 6-per-frame ramp, which
      // covers lossy VP8/JPEG drift without tolerating a wrong frame.
      expect(
        Math.abs(s.grey - s.want),
        `painted frame does not match currentTime at y=${s.y}\n${shown}`,
      ).toBeLessThanOrEqual(12);
    }

    // Strictly increasing greys prove real repaints rather than one static frame.
    for (let i = 1; i < samples.length; i++) {
      expect(samples[i].grey, `frame did not advance\n${shown}`).toBeGreaterThan(samples[i - 1].grey);
    }
  });

  test('does not touch currentTime before metadata arrives', async ({ page }) => {
    const errors = collectErrors(page);
    await openFixture(page, 'video.html');

    // #broken never loads, so it stands in for every video whose metadata has not
    // arrived yet: the engine must not write a time it cannot compute, and must
    // not throw trying.
    await scrollToY(page, 1400);
    await scrollToY(page, 1600);

    const row = await read<Row>(page);
    expect(row.brokenReadyState).toBe(0);
    expect(row.brokenTime, 'wrote currentTime before metadata was available').toBe(0);
    expect(row.brokenReadyCalls, 'onReady fired for a video that never loaded').toBe(0);
    expect(errors).toEqual([]);
  });

  test('reduced motion shows the end frame without scrolling', async ({ page }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await openFixture(page, 'video.html');
    await requireDecoder(page);

    await expect.poll(async () => (await read<Row>(page)).duration, { timeout: 5000 }).not.toBeNull();
    const row = await read<Row>(page);

    expect(row.scrollY).toBe(0);
    // The whole point of a scroll-scrubbed video is the motion, so under reduced
    // motion the engine settles on the final frame instead of animating.
    expect(row.currentTime).toBeCloseTo(DURATION, 1);
    expect(row.paused).toBe(true);
  });

  test('destroy() stops scrubbing', async ({ page }) => {
    await openFixture(page, 'video.html');
    await requireDecoder(page);
    await expect.poll(async () => (await read<Row>(page)).duration, { timeout: 5000 }).not.toBeNull();

    await scrollToY(page, 1400);
    const before = await read<Row>(page);
    expect(before.currentTime).toBeGreaterThan(0);

    await call(page, 'destroyClip');
    await scrollToY(page, T_END);
    const after = await read<Row>(page);

    expect(after.currentTime, 'a destroyed instance kept scrubbing').toBeCloseTo(
      before.currentTime,
      1,
    );
  });
});
