import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: { index: 'src/index.ts' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    clean: true,
    treeshake: true,
    minify: true,
  },
  {
    entry: { 'react/index': 'src/react/index.tsx' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    treeshake: true,
    minify: true,
    external: ['react'],
  },
  {
    entry: { 'vue/index': 'src/vue/index.ts' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    treeshake: true,
    minify: true,
    external: ['vue'],
  },
  {
    entry: { 'svelte/index': 'src/svelte/index.ts' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    treeshake: true,
    minify: true,
  },
  {
    entry: { 'solid/index': 'src/solid/index.ts' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    treeshake: true,
    minify: true,
    external: ['solid-js'],
  },
  {
    entry: { 'angular/index': 'src/angular/index.ts' },
    format: ['esm', 'cjs'],
    outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.mjs' }),
    dts: true,
    treeshake: true,
    minify: true,
  },
  {
    entry: { 'svg-scroll-draw': 'src/cdn.ts' },
    format: ['iife'],
    globalName: 'SvgScrollDraw',
    outDir: 'dist/cdn',
    minify: true,
    clean: false,
  },
]);
